blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blog/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.blogs, name='blogs'),
    path('blog/<int:blog_id>/', views.blog, name='blog'),
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('new_blog/', views.new_blog, name='new_blog'),
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete_blog')
]

blog/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register')
]

blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_edit = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='blog_owner')

    def __str__(self):
        return self.title

blog/users/models.py
from django.db import models

# Create your models here.

blog/blogs/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Text'}

blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Blog
from .forms import BlogForm


def index(request):
    return render(request, 'blogs/index.html')


@login_required
def blogs(request):
    blogs = Blog.objects.order_by('-date_edit')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)


@login_required
def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    context = {'blog': blog}
    return render(request, 'blogs/blog.html', context)


@login_required
def delete_blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    blog.delete()
    return redirect('blogs:blogs')


@login_required
def edit_blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    if request.method != 'POST':
        form = BlogForm(instance=blog)
    else:
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog_id)
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)


@login_required
def new_blog(request):
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog_post = form.save(commit=False)
            new_blog_post.owner = request.user
            new_blog_post.save()
            return redirect('blogs:blogs')
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blog/blogs/templates/blogs/base.html
{% load bootstrap4 %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <style>
        /* Добавляем пользовательские стили */
        .form-wrapper {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .form-wrapper h2 {
            margin-bottom: 20px;
            text-align: center;
        }

        .form-wrapper form {
            margin-bottom: 0;
        }

        .form-wrapper .form-group {
            margin-bottom: 20px;
        }

        .form-wrapper label {
            font-weight: bold;
        }

        .form-wrapper input[type="text"],
        .form-wrapper select,
        .form-wrapper textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        select,
        input[type="date"] {
            text-align: center;
        }

        input[type="date"] {
            /* width: calc(100% - 22px); */
            display: block;
            width: fit-content;
        }

        .form-wrapper input[type="checkbox"] {
            width: auto;
            margin-right: 5px;
        }

        .form-wrapper button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

        .form-wrapper button:hover {
            background-color: #0056b3;
        }

        .error-container {
            text-align: center;
        }

        .error-message {
            font-size: 24px;
            margin-bottom: 20px;
        }

        .error-cat {
            width: 300px;
            margin-bottom: 20px;
        }

        .back-link {
            font-size: 18px;
            color: #007bff;
            text-decoration: none;
        }

        .back-link:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:blogs' %}">Blogs</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text"> Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

blog/blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}
{% block content %}
<p>Blog:</p>
<div style="border: 1px solid black; padding: 10px; margin-bottom: 10px;" class="jumbotron">
    <h2 class="display-4">{{ blog.title }}</h2>
    <div class="form-group">
        <label class="form-label">Owner: </label>
        <p class="lead" style="display: contents;">{{ blog.owner }}</p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>Text:</b>
            <textarea class="form-control" readonly>
                {{ blog.text }}
            </textarea>
        </p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>Created Date:</b>
            <input type="date" id="created{{ blog.id }}" value="{{ blog.date_added|date:'Y-m-d' }}" readonly>
        </p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>Edit Date:</b>
            <input type="date" id="edit{{ blog.id }}" value="{{ blog.date_edit|date:'Y-m-d' }}" readonly>
        </p>
    </div>
    <p class="lead">
        <a class="btn btn-secondary" href="{% url 'blogs:edit_blog' blog.id %}">Edit blog</a>
    </p>
    <form action="{% url 'blogs:delete_blog' blog.id %}">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('Are you sure you want to delete this blog?')"
            class="btn btn-primary">Delete blog</button>
    </form>
</div>
{% endblock content %}

blog/blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}
{% block content %}
<p>blogs - <a href="{% url 'blogs:new_blog' %}">Add a new blog:</a></p>
<ul class="list-group">
    {% for blog in blogs %}
    <li style="border: 1px solid black; padding: 10px; margin-bottom: 10px; " class="list-group-item">
        <div class="form-group">
            <b><a class="text-decoration-none" href="{% url 'blogs:blog' blog.id %}" style="font-size: 20px;">{{ blog.title }}</a></b>
        </div>
        <div class="form-group">
            <label class="form-label">Owner: </label>
            <p class="lead" style="display: contents;">{{ blog.owner }}</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label">Created Date:</label>
                <input class="form-control" type="date" id="created{{ blog.id }}" value="{{ blog.date_added|date:'Y-m-d' }}" readonly style="width: auto;">
            </div>
            <div class="form-group">
                <label class="form-label">Edit Date:</label>
                <input class="form-control" type="date" id="edit{{ blog.id }}" value="{{ blog.date_edit|date:'Y-m-d' }}" readonly style="width: auto;">
            </div>
            <input type="hidden" value="{{ blog.id }}">
        </form>
    </li>
    {% empty %}
    <li class="list-group-item">No blogs ¯\_(ツ)_/¯</li>
    {% endfor %}
</ul>

{% endblock content %}

blog/blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% block content %}
<div class="form-wrapper">
    <p class="lead">
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
    </p>
    <h2 class="display-5">Edit Blog</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</div>
{% endblock content %}

blog/blogs/templates/blogs/error.html
{% extends "blogs/base.html" %}
{% block content %}
<div class="error-container">
    <img src="https://cataas.com/cat/gif" alt="Котик" class="error-cat">
    <p class="error-message">Что-то пошло не так...</p>
    <a href="/" class="back-link">Вернуться на главную страницу</a>
</div>
{% endblock content %}

blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% block content %}
<p>Blog helps you!</p>
{% endblock content %}

blog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% block content %}

<div class="form-wrapper">
    <h2>Add a new blog:</h2>
    <form action="{% url 'blogs:new_blog' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add blog</button>
    </form>
</div>

{% endblock content %}