task_tracker/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tasks.urls')),
]

task_tracker/tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    path('tasks/', views.tasks, name='tasks'),
    path('task/<int:task_id>/', views.task, name='task'),
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('new_task/', views.new_task, name='new_task'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task')
]

task_tracker/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register')
]

task_tracker/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Task(models.Model):
    PRIORITY_CHOICES = (
        ('Low', 'Низкий'),
        ('Medium', 'Средний'),
        ('High', 'Высокий'),
    )

    title = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField()
    completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='Низкий')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task_owner')
    assigner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='task_assigner')

    def __str__(self):
        return self.title

task_tracker/tasks/forms.py
from django import forms
from .models import Task
from datetime import date


class TaskForm(forms.ModelForm):
    date_picker = forms.DateInput(attrs=dict(type='date', value=date.today))
    start_date = forms.DateField(widget=date_picker, required=True)
    end_date = forms.DateField(widget=date_picker, required=True)

    class Meta:
        model = Task
        fields = [
            'title', 'description', 'start_date',
            'end_date', 'completed', 'priority', 'assigner'
        ]

        labels = {
            'title': 'Title',
            'description': 'Description',
            'start_date': 'Start date',
            'end_date': 'End date',
            'completed': 'Completed',
            'priority': 'Priority',
            'assigner': 'Assigner'
        }

task_tracker/tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Task
from .forms import TaskForm


def index(request):
    return render(request, 'tasks/index.html')

def index(request):
    return render(request, 'tasks/index.html')

@login_required
def tasks(request):
    tasks = Task.objects.filter(owner=request.user).order_by('start_date')
    context = {'tasks': tasks}
    return render(request, 'tasks/tasks.html', context)


@login_required
def task(request, task_id):
    task = Task.objects.get(id=task_id)
    context = {'task': task}
    return render(request, 'tasks/task.html', context)


@login_required
def delete_task(request, task_id):
    task = Task.objects.get(id=task_id)
    task.delete()
    return redirect('tasks:tasks')


@login_required
def edit_task(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method != 'POST':
        form = TaskForm(instance=task)
    else:
        form = TaskForm(instance=task, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:task', task_id=task_id)
    context = {'task': task, 'form': form}
    return render(request, 'tasks/edit_task.html', context)


@login_required
def new_task(request):
    if request.method != 'POST':
        form = TaskForm(initial={'assigner': request.user})
    else:
        form = TaskForm(data=request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect('tasks:tasks')
    context = {'form': form}
    return render(request, 'tasks/new_task.html', context)

task_tracker/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('tasks:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

task_tracker/tasks/templates/tasks/base.html
{% load bootstrap4 %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Task</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <style>
        /* Добавляем пользовательские стили */
        .form-wrapper {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .form-wrapper h2 {
            margin-bottom: 20px;
            text-align: center;
        }

        .form-wrapper form {
            margin-bottom: 0;
        }

        .form-wrapper .form-group {
            margin-bottom: 20px;
        }

        .form-wrapper label {
            font-weight: bold;
        }

        .form-wrapper input[type="text"],
        .form-wrapper select,
        .form-wrapper textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        select,
        input[type="date"] {
            text-align: center;
        }

        input[type="date"] {
            /* width: calc(100% - 22px); */
            display: block;
            width: fit-content;
        }

        .form-wrapper input[type="checkbox"] {
            width: auto;
            margin-right: 5px;
        }

        .form-wrapper button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

        .form-wrapper button:hover {
            background-color: #0056b3;
        }

        .error-container {
            text-align: center;
        }

        .error-message {
            font-size: 24px;
            margin-bottom: 20px;
        }

        .error-cat {
            width: 300px;
            margin-bottom: 20px;
        }

        .back-link {
            font-size: 18px;
            color: #007bff;
            text-decoration: none;
        }

        .back-link:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'tasks:index' %}">
            Task</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tasks:tasks' %}">Tasks</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text"> Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

task_tracker/tasks/templates/tasks/edit_task.html
{% extends "tasks/base.html" %}
{% block content %}
<div class="form-wrapper">
    <p class="lead">
        <a href="{% url 'tasks:task' task.id %}">{{ task.title }}</a>
    </p>
    <h2 class="display-5">Edit Task</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</div>
{% endblock content %}

task_tracker/tasks/templates/tasks/error.html
{% extends "tasks/base.html" %}
{% block content %}
<div class="error-container">
    <img src="https://cataas.com/cat/gif" alt="Котик" class="error-cat">
    <p class="error-message">Что-то пошло не так...</p>
    <a href="/" class="back-link">Вернуться на главную страницу</a>
</div>
{% endblock content %}

task_tracker/tasks/templates/tasks/index.html
{% extends "tasks/base.html" %}
{% block content %}
<p>Task helps you!</p>
{% endblock content %}

task_tracker/tasks/templates/tasks/new_task.html
{% extends "tasks/base.html" %}
{% block content %}

<div class="form-wrapper">
    <h2>Add a new task:</h2>
    <form action="{% url 'tasks:new_task' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add task</button>
    </form>
</div>

{% endblock content %}

task_tracker/tasks/templates/tasks/task.html
{% extends "tasks/base.html" %}
{% block content %}
<p>Task:</p>
<div style="border: 1px solid black; padding: 10px; margin-bottom: 10px;" class="jumbotron">
    <h2 class="display-4">{{ task.title }}</h2>
    <div class="form-group">
        <label class="form-label">Assigner: </label>
        <p class="lead" style="display: contents;">{{ task.assigner }}</p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>Description:</b>
            <textarea class="form-control" readonly>
                {{ task.description }}
            </textarea>
        </p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>Start Date:</b>
            <input type="date" id="start_date{{ task.id }}" value="{{ task.start_date|date:'Y-m-d' }}" readonly>
        </p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>End Date:</b>
            <input type="date" id="end_date{{ task.id }}" value="{{ task.end_date|date:'Y-m-d' }}" readonly>
        </p>
    </div>
    <div class="form-group">
        <p class="lead">
            <b>Priority:</b>
            <i>{{ task.get_priority_display }}</i>
        </p>
    </div>
    <div class="form-group">
        <p class="lead">
            <input type="checkbox" id="completed{{ task.id }}" name="completed" {% if task.completed %}checked{% endif %}
                disabled>
            <b>Completed</b>
        </p>
    </div>
    <p class="lead">
        <a class="btn btn-secondary" href="{% url 'tasks:edit_task' task.id %}">Edit task</a>
    </p>
    <form action="{% url 'tasks:delete_task' task.id %}">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('Are you sure you want to delete this task?')"
            class="btn btn-primary">Delete task</button>
    </form>
</div>
{% endblock content %}

task_tracker/tasks/templates/tasks/tasks.html
{% extends "tasks/base.html" %}
{% block content %}
<p>Tasks - <a href="{% url 'tasks:new_task' %}">Add a new task:</a></p>
<ul class="list-group">
    {% for task in tasks %}
    <li style="border: 1px solid black; padding: 10px; margin-bottom: 10px; " class="list-group-item">
        <div class="form-group">
            <b><a class="text-decoration-none" href="{% url 'tasks:task' task.id %}" style="font-size: 20px;">{{ task.title }}</a></b>
        </div>
        <div class="form-group">
            <label class="form-label">Assigner: </label>
            <p class="lead" style="display: contents;">{{ task.assigner }}</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label">Start Date:</label>
                <input class="form-control" type="date" id="start_date{{ task.id }}" value="{{ task.start_date|date:'Y-m-d' }}" readonly style="width: auto;">
            </div>
            <div class="form-group">
                <label class="form-label">End Date:</label>
                <input class="form-control" type="date" id="end_date{{ task.id }}" value="{{ task.end_date|date:'Y-m-d' }}" readonly style="width: auto;">
            </div>
            <br>
            <label>Priority:</label>
            <i>{{ task.get_priority_display }}</i>
            <br>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="completed{{ task.id }}" {% if task.completed%}checked{% endif %} disabled>
                <label class="form-check-label">Completed</label>
            </div>
            <input type="hidden" value="{{ task.id }}">
        </form>
    </li>
    {% empty %}
    <li class="list-group-item">No tasks ¯\_(ツ)_/¯</li>
    {% endfor %}
</ul>

{% endblock content %}